# This is a config for E2B sandbox template.
# You can use template ID (gh7vbsnj8cz9s2qrfpau) or template name (vibe-nextjs-thao) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-thao") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-thao") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-thao')

team_id = "650e2118-f6c4-418b-aef4-482050c99a63"
start_command = "./compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-thao"
template_id = "gh7vbsnj8cz9s2qrfpau"
